### ISSUE TITLE
请问作者提供的@jogle_channel_bot可以只显示点赞按钮不显示评论消息吗？

### ISSUE THREAD

**Issue by zzzop** [JogleLew/channel-helper-bot#15]
在/option里配置mode为0后就关闭了整个bot的功能

**Comment by JogleLew** [comment]
不需要评论功能的话， [@like](https://t.me/like) 更好用

**Comment by zzzop** [comment]
> 不需要评论功能的话， [@like](https://t.me/like) 更好用

好的，谢谢。主要是@like没有自动回复的功能，我再研究一下
