### ISSUE TITLE
被别人回复评论的消息时无跳转

### ISSUE THREAD

**Issue by blucartfhg** [JogleLew/channel-helper-bot#16]
我遇到了一个问题。

在非自己所有的channel下，如果我回复的消息msg1，被另一个人回复msg2，我可以收到bot私发我的，我收到了回复，这样的提示。

我觉得这里，可以添加一个链接，让我直接跳转到这个channel中我被回复的那里。

现在没有这个，所以我只能一个一个channel找。
如果不麻烦的话，辛苦您添加一下，可否？
谢谢。

**Comment by JogleLew** [comment]
已解决 [commit 9b1c556b577e7ee2465703f283c3834e19eadafd](https://github.com/JogleLew/channel-helper-bot/commit/9b1c556b577e7ee2465703f283c3834e19eadafd)

**Comment by blucartfhg** [comment]
感谢。
