### ISSUE TITLE
能否实现找到评论者？

### ISSUE THREAD

**Issue by Sfssup** [JogleLew/channel-helper-bot#17]
现在只能通过名字找到对方
能否实现频道拥有者可以通过消息来源找到评论者？即使这个人改了名字
另外就是封禁，是禁止别人评论还是在频道内封禁他？似乎是前者

**Comment by JogleLew** [comment]
考虑到隐私性问题，在 bot 发送的内容中，不会以任何形式泄漏用户的 ID，即不提供找人的功能。
使用封禁功能时，会通过用户 ID 判断是否应该阻止用户在频道内评论，修改名字不会影响封禁。
