### ISSUE TITLE
转发时，超链接文字会自动丢失。

### ISSUE THREAD

**Issue by blucartfhg** [JogleLew/channel-helper-bot#18]
您好，我又来提issue了。

一个channel中，发表了一个带有图片和超链接文字的消息，在经过机器人转发（自动beta）后，会自动丢失掉文字的超链接…

**Comment by JogleLew** [comment]
无法复现，请提供具体消息示例

**Comment by blucartfhg** [comment]
源 https://t.me/testforcommentbot1/3
出现link丢失 https://t.me/testforcommentbot2/6

**Comment by JogleLew** [comment]
感谢，已修复 [commit 9acb55bb55fa3731b00fdb51ae226d5ac39c01a5](https://github.com/JogleLew/channel-helper-bot/commit/9acb55bb55fa3731b00fdb51ae226d5ac39c01a5)
