### ISSUE TITLE
A huge bug...

### ISSUE THREAD

**Issue by morsecn** [JogleLew/channel-helper-bot#19]
Channel里进行评论的用户，名字如果过长，频道管理员就无法在bot中删除其讯息或者封禁此用户（无法显示）。且名字过长易影响版面，可以考虑修复或者把直接把所有评论的用户名进行缩减（或者添加此选项）。感谢！

**Comment by JogleLew** [comment]
已解决 [commit e5d67cb0946a29afbd0ad7343693043a90d4e7d9](https://github.com/JogleLew/channel-helper-bot/commit/e5d67cb0946a29afbd0ad7343693043a90d4e7d9)
