### ISSUE TITLE
是不是可以支持一下国际化？

### ISSUE THREAD

**Issue by greatghoul** [JogleLew/channel-helper-bot#2]
希望评论的按钮什么的，可以配置成英文

**Comment by JogleLew** [comment]
其实在初期是有做国际化的考虑，数据库里也预留了相应的字段，但后来发现国际化可能还需要对交互逻辑做一些调整，所以就搁置了。最近应该也不会考虑做这个。如果有需要的话，可以自行修改`helper_string.py`里的字段，另开启一个bot。

**Comment by JogleLew** [comment]
Done.
