### ISSUE TITLE
频道订阅人数超过200之后无法邀请机器人进频道

### ISSUE THREAD

**Issue by Latezly** [JogleLew/channel-helper-bot#29]
![image](https://user-images.githubusercontent.com/17759624/102965617-2ca63d80-4529-11eb-9a6b-50c0d8016f2b.png)
如图所示，不知道机器人能不能走私邀？

**Comment by JogleLew** [comment]
请在频道设置里<b>添加管理员</b> ，搜索bot的username并选择bot作为管理员。bot无法通过频道拉人的方式进入频道。
<del>PS：官方的评论功能它不香么</del>

**Comment by Latezly** [comment]
唔 没注意到还可以这样操作  多谢（捂脸
