### ISSUE TITLE
图片啥的能直接转换成超链接吗？

### ISSUE THREAD

**Issue by coderykw** [JogleLew/channel-helper-bot#3]

**Comment by JogleLew** [comment]
我觉得那样不美观。
评论可以发送图片，贴纸，甚至是视频，bot也记录下了相应的id，但是评论区确实没法显示这些。至于如何展现这些内容，还得容我再考虑下。

**Comment by JogleLew** [comment]
已完成一个简单的图片/sticker的预览功能。请在“显示更多消息”中，选择相应的消息内容，进行查看。
