### ISSUE TITLE
新版本支持库的重要bug

### ISSUE THREAD

**Issue by SakuraPie** [JogleLew/channel-helper-bot#32]
python-telegram-bot版本在13.2（当前最新版）时，显示所有评论--->开始/start--->点击消息列表中的按钮后，无法发送下一条消息（./callback_query.py 第64行所应发送的消息）。此问题在支持库版本为12.8时不存在。

**Comment by SakuraPie** [comment]
<img width="807" alt="截屏2021-02-10 下午7 17 35" src="https://user-images.githubusercontent.com/48736374/107504302-0d956500-6bd6-11eb-950a-9eccc0e766fb.png">
VSCode调试报错如图。原因是在./callback_query.py的send_message函数中传入了错误参数：message_id。

已提交PR：/pull/33

**Comment by SakuraPie** [comment]
<img width="807" alt="截屏2021-02-10 下午7 17 35" src="https://user-images.githubusercontent.com/48736374/107504762-be9bff80-6bd6-11eb-9c29-bdd96c233847.png">

VSCode调试报错如图。原因是在./callback_query.py的send_message函数中传入了错误参数：message_id。

已提交PR：/pull/33

**Comment by SakuraPie** [comment]
小吐槽：旧版本一直没报错真是奇迹

**Comment by JogleLew** [comment]
#33 Merged
