### ISSUE TITLE
當轉傳來源用戶隱藏了帳號，來源顯示會壞掉 

### ISSUE THREAD

**Issue by jimchen5209** [JogleLew/channel-helper-bot#5]
![圖片](https://user-images.githubusercontent.com/10269287/55721249-696c9100-5a35-11e9-9e11-c2d3284652c5.png)

https://t.me/HiddenSender/ 是用戶隱藏帳號時會替代的東西

**Comment by JogleLew** [comment]
这种情况下只能改成显示名字了

**Comment by jimchen5209** [comment]
不過現在已經不是顯示成頻道了
而是forward_sender_name

**Comment by JogleLew** [comment]
Telegram 似乎又更改了隐藏来源的消息的字段信息，而且不知道未来还是否会有其他的变化。好在 bot 还能正常工作，暂且先这样吧。
