### ISSUE TITLE
发现有大量广告党利用评论区宣传他们的群

### ISSUE THREAD

**Issue by tjsky** [JogleLew/channel-helper-bot#6]
目前发现很多广告党，发现有此bot的频道就这样干：
加频道，发他群组的邀请链接，退出频道。

因为他已经退群，管理也没法封他了。

管理手动修改评论区删除链接。
再有新评论后，他那条还是会显示出来。

下次有新评论区他回来再来一套，
加频道发链接退频道。管理根本拿这个号没办法。
（怀疑埋伏了大号在频道内）

我大致想了下解决办法：
评论禁止含有链接？
用户在频道内的第一次评论先审后发？
管理可以给自己群组加黑名单，有些人不能评论？
管理可以删除某条评论？

**Comment by JogleLew** [comment]
评论禁止含有链接？
不好

用户在频道内的第一次评论先审后发？
麻烦

管理可以给自己群组加黑名单，有些人不能评论？
可以考虑

管理可以删除某条评论？
可以考虑

**Comment by JogleLew** [comment]
删除消息功能和黑名单功能已完成。请在“显示更多消息”中，选择相应的消息内容，进行操作。
