### ISSUE TITLE
使用自动模式(beta)时是否可以删除评论区?

### ISSUE THREAD

**Issue by Rongronggg9** [JogleLew/channel-helper-bot#8]
有时候有些消息不想要评论区，先切换模式再发送又过于繁琐，可否发送消息后删除评论区?

**Comment by JogleLew** [comment]
可以

**Comment by Rongronggg9** [comment]
我可能说得不够明确，当这条消息还未被任何人评论时，显示的是消息下方的评论按钮。
我没有找到在不添加评论的情况下删除评论按钮的方法，只能添加评论后待评论区出现且评论按钮移动到评论区后再删除，这样才能消去评论按钮。
